// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package hu.modsstore.model.dto;

public class FelhasznaloBuilder extends
		FelhasznaloBuilderBase<FelhasznaloBuilder> {
	public static FelhasznaloBuilder felhasznalo() {
		return new FelhasznaloBuilder();
	}

	public FelhasznaloBuilder() {
		super(new Felhasznalo());
	}

	public Felhasznalo build() {
		return getInstance();
	}
}

class FelhasznaloBuilderBase<GeneratorT extends FelhasznaloBuilderBase<GeneratorT>> {
	private Felhasznalo instance;

	protected FelhasznaloBuilderBase(Felhasznalo aInstance) {
		instance = aInstance;
	}

	protected Felhasznalo getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Long aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withFelhasznaloNev(String aValue) {
		instance.setFelhasznaloNev(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withJelszo(String aValue) {
		instance.setJelszo(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSo(String aValue) {
		instance.setSo(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTelefonszam(String aValue) {
		instance.setTelefonszam(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withIranyitoszam(String aValue) {
		instance.setIranyitoszam(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withVaros(String aValue) {
		instance.setVaros(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUtca(String aValue) {
		instance.setUtca(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withHazszam(String aValue) {
		instance.setHazszam(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEmelet(String aValue) {
		instance.setEmelet(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAjto(String aValue) {
		instance.setAjto(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEmail(String aValue) {
		instance.setEmail(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withKartyaszam(String aValue) {
		instance.setKartyaszam(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSzerepkor(Szerepkor aValue) {
		instance.setSzerepkor(aValue);

		return (GeneratorT) this;
	}

	public SzerepkorSzerepkorBuilder withSzerepkor() {
		Szerepkor obj = new Szerepkor();

		withSzerepkor(obj);

		return new SzerepkorSzerepkorBuilder(obj);
	}

	public class SzerepkorSzerepkorBuilder extends
			SzerepkorBuilderBase<SzerepkorSzerepkorBuilder> {
		public SzerepkorSzerepkorBuilder(Szerepkor aInstance) {
			super(aInstance);
		}

		@SuppressWarnings("unchecked")
		public GeneratorT endSzerepkor() {
			return (GeneratorT) FelhasznaloBuilderBase.this;
		}
	}

	public static class SzerepkorBuilderBase<GeneratorT extends SzerepkorBuilderBase<GeneratorT>> {
		private Szerepkor instance;

		protected SzerepkorBuilderBase(Szerepkor aInstance) {
			instance = aInstance;
		}

		protected Szerepkor getInstance() {
			return instance;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withId(Long aValue) {
			instance.setId(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withNev(String aValue) {
			instance.setNev(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withLeiras(String aValue) {
			instance.setLeiras(aValue);

			return (GeneratorT) this;
		}
	}
}
